import { houseMatchesSet, type HouseSet } from "@/lib/house-set";
import type { PublicHouse } from "@/lib/types";
import shippedMonsterIds from "@/lib/gem-monsters-shipped.json";

/** Generated by scripts/write-gem-monsters-shipped.mjs from public/gem-monsters/*.glb */
const SHIPPED_MONSTER_IDS = new Set(shippedMonsterIds as string[]);

/** Full pool (Akochan pack + dragon) — used when GEM_MONSTERS_DRAGON_ONLY is false. */
export const GEM_MONSTER_CATALOG = [
  {
    id: "dragon",
    glbPath: "/gem-monsters/dragon.glb",
    posterPath: "/gem-monsters/dragon-poster.png",
    labelHe: "דרקון",
    petNameHe: "דרקי הדרקון",
  },
  {
    id: "black-cat",
    glbPath: "/gem-monsters/black-cat.glb",
    posterPath: "/gem-monsters/black-cat-poster.png",
    labelHe: "חתול שחור",
    petNameHe: "מיו החתול",
  },
  {
    id: "candy-corn",
    glbPath: "/gem-monsters/candy-corn.glb",
    posterPath: "/gem-monsters/candy-corn-poster.png",
    labelHe: "תירס ממתק",
    petNameHe: "קורני התירס",
  },
  {
    id: "eyeball",
    glbPath: "/gem-monsters/eyeball.glb",
    posterPath: "/gem-monsters/eyeball-poster.png",
    labelHe: "עין",
    petNameHe: "גלגל העין",
  },
  {
    id: "frankie",
    glbPath: "/gem-monsters/frankie.glb",
    posterPath: "/gem-monsters/frankie-poster.png",
    labelHe: "פרנקי",
    petNameHe: "פרנקי החביב",
  },
  {
    id: "ghost",
    glbPath: "/gem-monsters/ghost.glb",
    posterPath: "/gem-monsters/ghost-poster.png",
    labelHe: "רוח",
    petNameHe: "רפי הרוח",
  },
  {
    id: "ghost-hound",
    glbPath: "/gem-monsters/ghost-hound.glb",
    posterPath: "/gem-monsters/ghost-hound-poster.png",
    labelHe: "רוח כלב",
    petNameHe: "לבון כלב הרוח",
  },
  {
    id: "imp",
    glbPath: "/gem-monsters/imp.glb",
    posterPath: "/gem-monsters/imp-poster.png",
    labelHe: "שדון",
    petNameHe: "קונקי השדון",
  },
  {
    id: "mummy",
    glbPath: "/gem-monsters/mummy.glb",
    posterPath: "/gem-monsters/mummy-poster.png",
    labelHe: "מומיה",
    petNameHe: "מומו המומיה",
  },
  {
    id: "mushroom",
    glbPath: "/gem-monsters/mushroom.glb",
    posterPath: "/gem-monsters/mushroom-poster.png",
    labelHe: "פטרייה",
    petNameHe: "פטריק הפטרייה",
  },
  {
    id: "potion-slime",
    glbPath: "/gem-monsters/potion-slime.glb",
    posterPath: "/gem-monsters/potion-slime-poster.png",
    labelHe: "סליים",
    petNameHe: "גלי הסליים",
  },
  {
    id: "pumpkin",
    glbPath: "/gem-monsters/pumpkin.glb",
    posterPath: "/gem-monsters/pumpkin-poster.png",
    labelHe: "דלעת",
    petNameHe: "דלעל הדלעת",
  },
  {
    id: "raven",
    glbPath: "/gem-monsters/raven.glb",
    posterPath: "/gem-monsters/raven-poster.png",
    labelHe: "עורב",
    petNameHe: "קרקר העורב",
  },
  {
    id: "reaper",
    glbPath: "/gem-monsters/reaper.glb",
    posterPath: "/gem-monsters/reaper-poster.png",
    labelHe: "קוצר",
    petNameHe: "גורי הקוצר",
  },
  {
    id: "skeleton",
    glbPath: "/gem-monsters/skeleton.glb",
    posterPath: "/gem-monsters/skeleton-poster.png",
    labelHe: "שלד",
    petNameHe: "עצמון השלד",
  },
  {
    id: "spider",
    glbPath: "/gem-monsters/spider.glb",
    posterPath: "/gem-monsters/spider-poster.png",
    labelHe: "עכביש",
    petNameHe: "עכי העכביש",
  },
  {
    id: "vampire-bat",
    glbPath: "/gem-monsters/vampire-bat.glb",
    posterPath: "/gem-monsters/vampire-bat-poster.png",
    labelHe: "עטלף",
    petNameHe: "ווינקי העטלף",
  },
  {
    id: "werewolf",
    glbPath: "/gem-monsters/werewolf.glb",
    posterPath: "/gem-monsters/werewolf-poster.png",
    labelHe: "שועל",
    petNameHe: "לבי השועל",
  },
  {
    id: "zombie",
    glbPath: "/gem-monsters/zombie.glb",
    posterPath: "/gem-monsters/zombie-poster.png",
    labelHe: "זומבי",
    petNameHe: "זוזו הזומבי",
  },
] as const;

export type GemMonsterId = (typeof GEM_MONSTER_CATALOG)[number]["id"];

const MODELS_ON_DISK = GEM_MONSTER_CATALOG.filter((m) => SHIPPED_MONSTER_IDS.has(m.id));

/** True when only one pet GLB is deployed — every house gets that model. */
export const GEM_MONSTERS_DRAGON_ONLY = MODELS_ON_DISK.length <= 1;

export const GEM_MONSTER_MODELS = (
  MODELS_ON_DISK.length > 0 ? MODELS_ON_DISK : [GEM_MONSTER_CATALOG[0]!]
) as readonly (typeof GEM_MONSTER_CATALOG)[number][];

const DEFAULT_MONSTER = GEM_MONSTER_CATALOG[0]!;

function hashHouseId(id: string) {
  let h = 2166136261;
  for (let i = 0; i < id.length; i += 1) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function hashMonsterForHouse(houseId: string): GemMonsterId {
  const pool = GEM_MONSTER_MODELS;
  const idx = hashHouseId(houseId) % pool.length;
  return pool[idx]!.id;
}

/** Houses that can hide a gem on the map (real mode drops rehearsal stubs). */
export function gemHuntMapHouses(houses: PublicHouse[], houseSet: HouseSet = "real") {
  return houses.filter((house) => houseMatchesSet(house, houseSet));
}

/**
 * One monster per map house — first `pool.length` houses (by id) each get a unique pet,
 * then hash for extras. When there are at least as many houses as shipped GLBs, every sticker appears.
 */
export function buildGemMonsterAssignment(
  mapHouses: readonly Pick<PublicHouse, "id" | "theme" | "kind">[],
): ReadonlyMap<string, GemMonsterId> {
  if (GEM_MONSTERS_DRAGON_ONLY) {
    const only = GEM_MONSTER_MODELS[0]!.id;
    return new Map(mapHouses.map((house) => [house.id, only]));
  }
  const pool = GEM_MONSTER_MODELS;
  const sorted = [...mapHouses].sort((a, b) => a.id.localeCompare(b.id, "he"));
  const out = new Map<string, GemMonsterId>();
  for (let i = 0; i < sorted.length; i += 1) {
    const house = sorted[i]!;
    void house.theme;
    void house.kind;
    out.set(
      house.id,
      i < pool.length ? pool[i]!.id : hashMonsterForHouse(house.id),
    );
  }
  return out;
}

let activeAssignment: ReadonlyMap<string, GemMonsterId> | null = null;
let activeAssignmentKey = "";

/** Keep map + album + collect in sync — call when the gem-eligible house list changes. */
export function syncGemMonsterAssignment(
  mapHouses: readonly Pick<PublicHouse, "id" | "theme" | "kind">[],
) {
  const key = mapHouses
    .map((house) => house.id)
    .sort((a, b) => a.localeCompare(b, "he"))
    .join("\0");
  if (key === activeAssignmentKey && activeAssignment) return activeAssignment;
  activeAssignment = buildGemMonsterAssignment(mapHouses);
  activeAssignmentKey = key;
  return activeAssignment;
}

export function gemMonsterForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">): GemMonsterId {
  if (GEM_MONSTERS_DRAGON_ONLY) {
    return GEM_MONSTER_MODELS[0]!.id;
  }
  void house.theme;
  void house.kind;
  const assigned = activeAssignment?.get(house.id);
  if (assigned) return assigned;
  return hashMonsterForHouse(house.id);
}

export function gemMonsterMeta(monsterId: GemMonsterId) {
  return GEM_MONSTER_CATALOG.find((m) => m.id === monsterId) ?? DEFAULT_MONSTER;
}

/** Slight per-house hue so repeats feel a bit different on the bag map. */
export function gemMonsterTint(houseId: string) {
  const hue = (hashHouseId(houseId) % 360) / 360;
  return { hue, saturation: 0.35, lightness: 0.08 };
}

type GemCatalogEntry = (typeof GEM_MONSTER_CATALOG)[number];

function findMonsterEntry(id: string): GemCatalogEntry | undefined {
  return GEM_MONSTER_CATALOG.find((m) => m.id === id);
}

/** Cute display name (e.g. «עכי העכביש»). */
export function gemLabelHe(variantOrMonsterId: string) {
  const meta = findMonsterEntry(variantOrMonsterId);
  return meta ? meta.petNameHe : DEFAULT_MONSTER.petNameHe;
}

/** Short species label when needed. */
export function gemSpeciesLabelHe(variantOrMonsterId: string) {
  const meta = findMonsterEntry(variantOrMonsterId);
  return meta ? meta.labelHe : DEFAULT_MONSTER.labelHe;
}

export function countGemEligibleHouses(houses: PublicHouse[], houseSet: HouseSet = "real") {
  return gemHuntMapHouses(houses, houseSet).length;
}

/** All shipped sticker slots (not deduped by hash collisions on the map). */
export function gemAlbumStickerPool(): readonly GemCatalogEntry[] {
  return GEM_MONSTER_MODELS;
}

/** @deprecated Use gemAlbumStickerPool — album shows every shipped GLB, not hash-unique subset. */
export function gemAlbumMonstersForMap(_houses: PublicHouse[]): GemCatalogEntry[] {
  return [...gemAlbumStickerPool()];
}

export type GemCollectionStamp = { houseId: string; gemType: string; collectedAt: number };

/** Monster filled in the album when any matching house gem was collected. */
export function isGemAlbumMonsterCollected(
  monsterId: GemMonsterId,
  collected: GemCollectionStamp[],
  housesById: ReadonlyMap<string, Pick<PublicHouse, "id" | "theme" | "kind">>,
) {
  for (const entry of collected) {
    if (entry.gemType === monsterId) return true;
    const house = housesById.get(entry.houseId);
    if (house && gemMonsterForHouse(house) === monsterId) return true;
  }
  return false;
}

export type GemFamily = "monster";

export function gemFamilyForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">): GemFamily {
  void house;
  return "monster";
}

/** @deprecated Use gemMonsterForHouse */
export function gemVariantForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">) {
  return gemMonsterForHouse(house);
}

export function gemVariantMeta(id: string) {
  const meta = gemMonsterMeta(id as GemMonsterId);
  return { id: meta.id, family: "monster" as const, labelHe: meta.petNameHe };
}
