import { distanceMeters } from "@/lib/geo";
import { clusterAddressKeyForHouse } from "@/lib/house-clusters";
import { houseMatchesSet, type HouseSet } from "@/lib/house-set";
import type { PublicHouse } from "@/lib/types";

/** Target spacing between two houses with the same pet (when the map allows it). */
export const GEM_REPEAT_MIN_SPACING_M = 300;

export type GemAssignHouse = Pick<PublicHouse, "id" | "theme" | "kind" | "lat" | "lng" | "address">;
import shippedMonsterIds from "@/lib/gem-monsters-shipped.json";

/** Generated by scripts/write-gem-monsters-shipped.mjs from public/gem-monsters/*.glb */
const SHIPPED_MONSTER_IDS = new Set(shippedMonsterIds as string[]);

/** Full pool (Akochan pack + dragon) — used when GEM_MONSTERS_DRAGON_ONLY is false. */
export const GEM_MONSTER_CATALOG = [
  {
    id: "dragon",
    glbPath: "/gem-monsters/dragon.glb",
    posterPath: "/gem-monsters/dragon-poster.png",
    labelHe: "דרקון",
    petNameHe: "דרקי הדרקון",
  },
  {
    id: "black-cat",
    glbPath: "/gem-monsters/black-cat.glb",
    posterPath: "/gem-monsters/black-cat-poster.png",
    labelHe: "חתול שחור",
    petNameHe: "מיו החתול",
  },
  {
    id: "candy-corn",
    glbPath: "/gem-monsters/candy-corn.glb",
    posterPath: "/gem-monsters/candy-corn-poster.png",
    labelHe: "תירס ממתק",
    petNameHe: "קורני התירס",
  },
  {
    id: "eyeball",
    glbPath: "/gem-monsters/eyeball.glb",
    posterPath: "/gem-monsters/eyeball-poster.png",
    labelHe: "עין",
    petNameHe: "גלגל העין",
  },
  {
    id: "frankie",
    glbPath: "/gem-monsters/frankie.glb",
    posterPath: "/gem-monsters/frankie-poster.png",
    labelHe: "פרנקי",
    petNameHe: "פרנקי החביב",
  },
  {
    id: "ghost",
    glbPath: "/gem-monsters/ghost.glb",
    posterPath: "/gem-monsters/ghost-poster.png",
    labelHe: "רוח",
    petNameHe: "רפי הרוח",
  },
  {
    id: "ghost-hound",
    glbPath: "/gem-monsters/ghost-hound.glb",
    posterPath: "/gem-monsters/ghost-hound-poster.png",
    labelHe: "רוח כלב",
    petNameHe: "לבון כלב הרוח",
  },
  {
    id: "imp",
    glbPath: "/gem-monsters/imp.glb",
    posterPath: "/gem-monsters/imp-poster.png",
    labelHe: "שדון",
    petNameHe: "קונקי השובב",
  },
  {
    id: "mummy",
    glbPath: "/gem-monsters/mummy.glb",
    posterPath: "/gem-monsters/mummy-poster.png",
    labelHe: "מומיה",
    petNameHe: "מומו המומיה",
  },
  {
    id: "mushroom",
    glbPath: "/gem-monsters/mushroom.glb",
    posterPath: "/gem-monsters/mushroom-poster.png",
    labelHe: "פטרייה",
    petNameHe: "פטריק הפטרייה",
  },
  {
    id: "potion-slime",
    glbPath: "/gem-monsters/potion-slime.glb",
    posterPath: "/gem-monsters/potion-slime-poster.png",
    labelHe: "סליים",
    petNameHe: "גלי הסליים",
  },
  {
    id: "pumpkin",
    glbPath: "/gem-monsters/pumpkin.glb",
    posterPath: "/gem-monsters/pumpkin-poster.png",
    labelHe: "דלעת",
    petNameHe: "דלעל הדלעת",
  },
  {
    id: "raven",
    glbPath: "/gem-monsters/raven.glb",
    posterPath: "/gem-monsters/raven-poster.png",
    labelHe: "עורב",
    petNameHe: "קרקר העורב",
  },
  {
    id: "reaper",
    glbPath: "/gem-monsters/reaper.glb",
    posterPath: "/gem-monsters/reaper-poster.png",
    labelHe: "קוצר",
    petNameHe: "גורי הקוצר",
  },
  {
    id: "skeleton",
    glbPath: "/gem-monsters/skeleton.glb",
    posterPath: "/gem-monsters/skeleton-poster.png",
    labelHe: "שלד",
    petNameHe: "עצמון השלד",
  },
  {
    id: "spider",
    glbPath: "/gem-monsters/spider.glb",
    posterPath: "/gem-monsters/spider-poster.png",
    labelHe: "עכביש",
    petNameHe: "עכי העכביש",
  },
  {
    id: "vampire-bat",
    glbPath: "/gem-monsters/vampire-bat.glb",
    posterPath: "/gem-monsters/vampire-bat-poster.png",
    labelHe: "עטלף",
    petNameHe: "ווינקי העטלף",
  },
  {
    id: "werewolf",
    glbPath: "/gem-monsters/werewolf.glb",
    posterPath: "/gem-monsters/werewolf-poster.png",
    labelHe: "שועל",
    petNameHe: "לבי השועל",
  },
  {
    id: "zombie",
    glbPath: "/gem-monsters/zombie.glb",
    posterPath: "/gem-monsters/zombie-poster.png",
    labelHe: "זומבי",
    petNameHe: "זומבי הזחל",
  },
] as const;

export type GemMonsterId = (typeof GEM_MONSTER_CATALOG)[number]["id"];

const MODELS_ON_DISK = GEM_MONSTER_CATALOG.filter((m) => SHIPPED_MONSTER_IDS.has(m.id));

/** True when only one pet GLB is deployed — every house gets that model. */
export const GEM_MONSTERS_DRAGON_ONLY = MODELS_ON_DISK.length <= 1;

export const GEM_MONSTER_MODELS = (
  MODELS_ON_DISK.length > 0 ? MODELS_ON_DISK : [GEM_MONSTER_CATALOG[0]!]
) as readonly (typeof GEM_MONSTER_CATALOG)[number][];

const DEFAULT_MONSTER = GEM_MONSTER_CATALOG[0]!;

function hashHouseId(id: string) {
  let h = 2166136261;
  for (let i = 0; i < id.length; i += 1) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function hashMonsterForHouse(houseId: string): GemMonsterId {
  const pool = GEM_MONSTER_MODELS;
  const idx = hashHouseId(houseId) % pool.length;
  return pool[idx]!.id;
}

function houseGeo(house: GemAssignHouse): { lat: number; lng: number } | null {
  if (
    typeof house.lat === "number" &&
    typeof house.lng === "number" &&
    Number.isFinite(house.lat) &&
    Number.isFinite(house.lng)
  ) {
    return { lat: house.lat, lng: house.lng };
  }
  return null;
}

function minDistToPoints(
  point: { lat: number; lng: number },
  points: readonly { lat: number; lng: number }[],
): number {
  if (points.length === 0) return Infinity;
  let min = Infinity;
  for (const p of points) {
    const d = distanceMeters(point, p);
    if (d < min) min = d;
  }
  return min;
}

function sameMonsterSpacingOk(
  separationM: number,
  sameTypeCount: number,
  enforceMin: boolean,
) {
  if (sameTypeCount === 0) return true;
  if (!enforceMin) return true;
  return separationM >= GEM_REPEAT_MIN_SPACING_M;
}

function pickMonsterForHouse(
  houseId: string,
  g: { lat: number; lng: number },
  pool: typeof GEM_MONSTER_MODELS,
  assignment: ReadonlyMap<string, GemMonsterId>,
  geoById: ReadonlyMap<string, { lat: number; lng: number }>,
  countByMonster: ReadonlyMap<GemMonsterId, number>,
  targetPerMonster: number,
  enforceMinSpacing: boolean,
): GemMonsterId {
  let bestMonster = pool[0]!.id;
  let bestScore = -Infinity;
  let bestCount = Infinity;
  let bestTie = 0;
  for (const entry of pool) {
    const monsterId = entry.id;
    const count = countByMonster.get(monsterId) ?? 0;
    if (count >= targetPerMonster + 1) continue;
    const sameType = monsterLocations(monsterId, assignment, geoById);
    const separation = minDistToPoints(g, sameType);
    if (!sameMonsterSpacingOk(separation, sameType.length, enforceMinSpacing)) continue;
    const tie = hashHouseId(`${houseId}\0${monsterId}`);
    const better =
      separation > bestScore ||
      (separation === bestScore && count < bestCount) ||
      (separation === bestScore && count === bestCount && tie > bestTie);
    if (better) {
      bestScore = separation;
      bestCount = count;
      bestTie = tie;
      bestMonster = monsterId;
    }
  }
  if (bestScore > -Infinity) return bestMonster;

  if (enforceMinSpacing) {
    return pickMonsterForHouse(
      houseId,
      g,
      pool,
      assignment,
      geoById,
      countByMonster,
      targetPerMonster,
      false,
    );
  }

  bestMonster = pool[0]!.id;
  bestScore = -Infinity;
  bestCount = Infinity;
  bestTie = 0;
  for (const entry of pool) {
    const monsterId = entry.id;
    const count = countByMonster.get(monsterId) ?? 0;
    const sameType = monsterLocations(monsterId, assignment, geoById);
    const separation = minDistToPoints(g, sameType);
    const tie = hashHouseId(`${houseId}\0${monsterId}`);
    if (
      separation > bestScore ||
      (separation === bestScore && count < bestCount) ||
      (separation === bestScore && count === bestCount && tie > bestTie)
    ) {
      bestScore = separation;
      bestCount = count;
      bestTie = tie;
      bestMonster = monsterId;
    }
  }
  return bestMonster;
}

function monsterLocations(
  monsterId: GemMonsterId,
  assignment: ReadonlyMap<string, GemMonsterId>,
  geoById: ReadonlyMap<string, { lat: number; lng: number }>,
): { lat: number; lng: number }[] {
  const out: { lat: number; lng: number }[] = [];
  for (const [houseId, mid] of assignment) {
    if (mid !== monsterId) continue;
    const g = geoById.get(houseId);
    if (g) out.push(g);
  }
  return out;
}

function buildGemMonsterAssignmentById(
  mapHouses: readonly GemAssignHouse[],
): ReadonlyMap<string, GemMonsterId> {
  const pool = GEM_MONSTER_MODELS;
  const sorted = [...mapHouses].sort((a, b) => a.id.localeCompare(b.id, "he"));
  const out = new Map<string, GemMonsterId>();
  for (let i = 0; i < sorted.length; i += 1) {
    const house = sorted[i]!;
    out.set(
      house.id,
      i < pool.length ? pool[i]!.id : hashMonsterForHouse(house.id),
    );
  }
  return out;
}

/** Spread pets across the play zone — avoid hash clusters of the same sticker. */
function buildGemMonsterAssignmentSpatial(
  mapHouses: readonly GemAssignHouse[],
): ReadonlyMap<string, GemMonsterId> {
  const pool = GEM_MONSTER_MODELS;
  const geoById = new Map<string, { lat: number; lng: number }>();
  const withGeo: GemAssignHouse[] = [];
  const noGeo: GemAssignHouse[] = [];
  for (const house of mapHouses) {
    const g = houseGeo(house);
    if (g) {
      geoById.set(house.id, g);
      withGeo.push(house);
    } else {
      noGeo.push(house);
    }
  }
  if (withGeo.length === 0) return buildGemMonsterAssignmentById(mapHouses);

  const assignment = new Map<string, GemMonsterId>();
  const unassigned = new Set(withGeo.map((h) => h.id));
  const allAssignedPoints: { lat: number; lng: number }[] = [];
  const countByMonster = new Map<GemMonsterId, number>();

  const bumpCount = (monsterId: GemMonsterId) => {
    countByMonster.set(monsterId, (countByMonster.get(monsterId) ?? 0) + 1);
  };

  const assign = (houseId: string, monsterId: GemMonsterId) => {
    assignment.set(houseId, monsterId);
    unassigned.delete(houseId);
    const g = geoById.get(houseId);
    if (g) allAssignedPoints.push(g);
    bumpCount(monsterId);
  };

  const seedCount = Math.min(pool.length, withGeo.length);
  for (let mi = 0; mi < seedCount; mi += 1) {
    const monsterId = pool[mi]!.id;
    let bestId: string | null = null;
    let bestScore = -1;
    let bestTie = 0;
    for (const houseId of unassigned) {
      const g = geoById.get(houseId)!;
      const score = minDistToPoints(g, allAssignedPoints);
      const tie = hashHouseId(`${houseId}\0seed\0${monsterId}`);
      if (score > bestScore || (score === bestScore && tie > bestTie)) {
        bestScore = score;
        bestTie = tie;
        bestId = houseId;
      }
    }
    if (bestId) assign(bestId, monsterId);
  }

  const remaining = [...unassigned].sort((a, b) => a.localeCompare(b, "he"));
  const targetPerMonster = Math.ceil(withGeo.length / pool.length);

  for (const houseId of remaining) {
    const g = geoById.get(houseId)!;
    const bestMonster = pickMonsterForHouse(
      houseId,
      g,
      pool,
      assignment,
      geoById,
      countByMonster,
      targetPerMonster,
      true,
    );
    assign(houseId, bestMonster);
  }

  if (noGeo.length > 0) {
    const sortedNoGeo = [...noGeo].sort((a, b) => a.id.localeCompare(b.id, "he"));
    for (const house of sortedNoGeo) {
      let bestMonster = hashMonsterForHouse(house.id);
      let bestCount = countByMonster.get(bestMonster) ?? 0;
      for (const entry of pool) {
        const count = countByMonster.get(entry.id) ?? 0;
        if (count < bestCount) {
          bestCount = count;
          bestMonster = entry.id;
        }
      }
      assign(house.id, bestMonster);
    }
  }

  return assignment;
}

/** Houses that can hide a gem on the map (real mode drops rehearsal stubs). */
export function gemHuntMapHouses(houses: PublicHouse[], houseSet: HouseSet = "real") {
  return houses.filter((house) => houseMatchesSet(house, houseSet));
}

/** @deprecated One carrier per address cluster — prefer {@link gemHousesForMap}. */
export function gemCarrierHousesForMap<T extends Pick<PublicHouse, "id" | "address">>(
  houses: readonly T[],
): T[] {
  const byCluster = new Map<string, T[]>();
  for (const house of houses) {
    const key = clusterAddressKeyForHouse(house);
    const list = byCluster.get(key);
    if (list) list.push(house);
    else byCluster.set(key, [house]);
  }
  const carriers: T[] = [];
  for (const group of byCluster.values()) {
    const picked = [...group].sort((a, b) => a.id.localeCompare(b.id, "he"))[0]!;
    carriers.push(picked);
  }
  return carriers.sort((a, b) => a.id.localeCompare(b.id, "he"));
}

/** Every eligible house gets its own map gem (including apartments / booths at one address). */
export function gemHousesForMap<T extends Pick<PublicHouse, "id" | "address">>(
  houses: readonly T[],
): T[] {
  return [...houses].sort((a, b) => a.id.localeCompare(b.id, "he"));
}

export type GemClusterSpread = { index: number; size: number };

let gemClusterSpreadByHouseId: ReadonlyMap<string, GemClusterSpread> = new Map();

function rebuildGemClusterSpread(houses: readonly Pick<PublicHouse, "id" | "address">[]) {
  const byCluster = new Map<string, Pick<PublicHouse, "id" | "address">[]>();
  for (const house of houses) {
    const key = clusterAddressKeyForHouse(house);
    const list = byCluster.get(key);
    if (list) list.push(house);
    else byCluster.set(key, [house]);
  }
  const spread = new Map<string, GemClusterSpread>();
  for (const group of byCluster.values()) {
    const sorted = [...group].sort((a, b) => a.id.localeCompare(b.id, "he"));
    const size = sorted.length;
    sorted.forEach((house, index) => {
      if (size > 1) spread.set(house.id, { index, size });
    });
  }
  gemClusterSpreadByHouseId = spread;
}

export function gemClusterSpreadForHouse(houseId: string): GemClusterSpread | null {
  return gemClusterSpreadByHouseId.get(houseId) ?? null;
}

/**
 * One monster per map house — first `pool.length` houses (by id) each get a unique pet,
 * then hash for extras. When there are at least as many houses as shipped GLBs, every sticker appears.
 */
export function buildGemMonsterAssignment(
  mapHouses: readonly GemAssignHouse[],
): ReadonlyMap<string, GemMonsterId> {
  const onMap = gemHousesForMap(mapHouses);
  if (GEM_MONSTERS_DRAGON_ONLY) {
    const only = GEM_MONSTER_MODELS[0]!.id;
    return new Map(onMap.map((house) => [house.id, only]));
  }
  for (const house of onMap) {
    void house.theme;
    void house.kind;
  }
  if (onMap.length <= 1) {
    const only = onMap[0];
    if (!only) return new Map();
    return new Map([[only.id, hashMonsterForHouse(only.id)]]);
  }
  return buildGemMonsterAssignmentSpatial(onMap);
}

let activeAssignment: ReadonlyMap<string, GemMonsterId> | null = null;
let activeAssignmentKey = "";

const GEM_ASSIGNMENT_ALGO = "spatial-v3-per-house";

/** Keep map + album + collect in sync — call when the gem-eligible house list changes. */
export function syncGemMonsterAssignment(mapHouses: readonly GemAssignHouse[]) {
  const key = `${GEM_ASSIGNMENT_ALGO}\0${mapHouses
    .map((house) => house.id)
    .sort((a, b) => a.localeCompare(b, "he"))
    .join("\0")}`;
  if (key === activeAssignmentKey && activeAssignment) return activeAssignment;
  rebuildGemClusterSpread(mapHouses);
  activeAssignment = buildGemMonsterAssignment(mapHouses);
  activeAssignmentKey = key;
  return activeAssignment;
}

export function houseHasMapGem(houseId: string) {
  if (!activeAssignment) return true;
  return activeAssignment.has(houseId);
}

export function gemMonsterForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">): GemMonsterId {
  if (GEM_MONSTERS_DRAGON_ONLY) {
    return GEM_MONSTER_MODELS[0]!.id;
  }
  void house.theme;
  void house.kind;
  const assigned = activeAssignment?.get(house.id);
  if (assigned) return assigned;
  return hashMonsterForHouse(house.id);
}

export function gemMonsterMeta(monsterId: GemMonsterId) {
  return GEM_MONSTER_CATALOG.find((m) => m.id === monsterId) ?? DEFAULT_MONSTER;
}

/** Slight per-house hue so repeats feel a bit different on the bag map. */
export function gemMonsterTint(houseId: string) {
  const hue = (hashHouseId(houseId) % 360) / 360;
  return { hue, saturation: 0.35, lightness: 0.08 };
}

type GemCatalogEntry = (typeof GEM_MONSTER_CATALOG)[number];

function findMonsterEntry(id: string): GemCatalogEntry | undefined {
  return GEM_MONSTER_CATALOG.find((m) => m.id === id);
}

/** Cute display name (e.g. «עכי העכביש»). */
export function gemLabelHe(variantOrMonsterId: string) {
  const meta = findMonsterEntry(variantOrMonsterId);
  return meta ? meta.petNameHe : DEFAULT_MONSTER.petNameHe;
}

/** Short species label when needed. */
export function gemSpeciesLabelHe(variantOrMonsterId: string) {
  const meta = findMonsterEntry(variantOrMonsterId);
  return meta ? meta.labelHe : DEFAULT_MONSTER.labelHe;
}

export function countGemEligibleHouses(houses: PublicHouse[], houseSet: HouseSet = "real") {
  return gemHousesForMap(gemHuntMapHouses(houses, houseSet)).length;
}

/** All shipped sticker slots (not deduped by hash collisions on the map). */
export function gemAlbumStickerPool(): readonly GemCatalogEntry[] {
  return GEM_MONSTER_MODELS;
}

/** @deprecated Use gemAlbumStickerPool — album shows every shipped GLB, not hash-unique subset. */
export function gemAlbumMonstersForMap(houses: PublicHouse[]): GemCatalogEntry[] {
  void houses;
  return [...gemAlbumStickerPool()];
}

export type GemCollectionStamp = { houseId: string; gemType: string; collectedAt: number };

/** Monster filled in the album when any matching house gem was collected. */
export function isGemAlbumMonsterCollected(
  monsterId: GemMonsterId,
  collected: GemCollectionStamp[],
  housesById: ReadonlyMap<string, Pick<PublicHouse, "id" | "theme" | "kind">>,
) {
  for (const entry of collected) {
    if (entry.gemType === monsterId) return true;
    const house = housesById.get(entry.houseId);
    if (house && gemMonsterForHouse(house) === monsterId) return true;
  }
  return false;
}

export type GemFamily = "monster";

export function gemFamilyForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">): GemFamily {
  void house;
  return "monster";
}

/** @deprecated Use gemMonsterForHouse */
export function gemVariantForHouse(house: Pick<PublicHouse, "id" | "theme" | "kind">) {
  return gemMonsterForHouse(house);
}

export function gemVariantMeta(id: string) {
  const meta = gemMonsterMeta(id as GemMonsterId);
  return { id: meta.id, family: "monster" as const, labelHe: meta.petNameHe };
}
